References for AboutTeam and nearly final AboutUs
ryeenii/t80sz pull request #3
Opened 2021-04-05 18:55 UTC by Fluffacorn

Just, penis and balls even. Something to note is AboutTeam.svx is NOT the final version, and is not meant to be put into use. It's simply outlining certain stuff for the staff so that whenever you finish the stuff for the site, we can work significantly faster.

2021-04-05 19:00 UTC, ryeenii commented on src/svelte-html/docs/AboutTeam.svx
> +<Header text="past staff" gradient="purple"/> <!-- gradient options: yellow, orange, purple, blue, green -->
preferentially remove the comment on the gradient options once you already used it

also, leave it as `yellow` for everything on the information page.

2021-04-05 19:01 UTC, ryeenii commented on src/svelte-html/docs/AboutTeam.svx
> +### ADMIN:
i would leave a h4 here considering it's a subcategory.

2021-04-05 19:01 UTC, ryeenii commented on src/svelte-html/docs/AboutTeam.svx
> +D Vana -Founder of The 80s Zone
i hope that lack of space wasn't intentional lmao

2021-04-05 19:03 UTC, ryeenii commented on src/svelte-html/docs/AboutTeam.svx
> +Willbot - Previous admin, currently mod
```suggestion
Willbot - Moderator (previously Admin)
```

2021-04-05 19:04 UTC, ryeenii commented on src/svelte-html/docs/AboutTeam.svx
> +Shira - Previous admin
```suggestion
Shira - Former admin
```

2021-04-05 19:04 UTC, ryeenii commented on src/svelte-html/docs/AboutTeam.svx
> +Doe - Puppeteer of Jem
```suggestion
Doe - Puppeteer of Jem (Former Admin)
```

2021-04-05 19:05 UTC, ryeenii commented on src/svelte-html/docs/AboutTeam.svx
> +Date of Hire: 11/17/17
```suggestion
Date of Hire: `11/17/17`
```
maybe blockquote could be used for day of hire/leave?

2021-04-05 19:08 UTC, ryeenii commented on src/svelte-html/docs/AboutTeam.svx
> +About: Ced joined the mod team after being promoted out of Loli Patroli, a group designed to moderate the undergoing lolicon problems in the porn channels. Ced faced backlash from members of the comm
```suggestion
About: Ced joined the mod team after being promoted out of Loli Patroli[hyperlink], a group designed to moderate the undergoing lolicon problems in the porn channels. Ced faced backlash from members of the community and mod team throughout his career for his ways of moderation such as leaving people in the timeout channels for several hours with no notice, attempting to migrate the community to a satellite server, and bullying members and moderators in the community.
```
maybe a hyperlink here? i don't know, wanna hear your thoughts

2021-04-05 19:12 UTC, ryeenii commented on src/svelte-html/docs/AboutUs.svx
> +So where did the community originate from? It all started on <span style="color:#FFE500">***September 20th, 2017***</span> when mashup youtuber <span style="color:#FFE500">***I am Jemboy***</span> ha
```
<span style="color:#FFE500">**September 20th, 2017**</span>
<span style="color:#FFE500">**I am Jemboy**</span>
<span style="color:#FFE500">**September 30th, 2017**</span>
<span style="color:#FFE500">**July 4th, 2018**</span>
<span style="color:#FFE500">**D Vana**</span>
<span style="color:#FFE500">**February 21st, 2019**</span>
<span style="color:#FFE500">**Skelly**</span>
```
pls remove le ibalics

2021-04-05 19:14 UTC, ryeenii approved these changes

2021-04-05 19:14 UTC, ryeenii requested changes
æ

2021-04-05 19:15 UTC, ryeenii commented
i fucked up that review, didn't wanted to approve it lol

2021-04-05 20:58 UTC, Fluffacorn commented on src/svelte-html/docs/AboutTeam.svx
> +### ADMIN:
We really only use these for managing our data, this is nowhere near complete and isn't even really a draft. I think it's fine for now.

2021-04-05 21:00 UTC, Fluffacorn commented on src/svelte-html/docs/AboutTeam.svx
> +Willbot - Previous admin, currently mod
Shorter and way more concise, I'll be accepting all changes similar to this.

2021-04-05 21:04 UTC, Fluffacorn commented on src/svelte-html/docs/AboutTeam.svx
> +Date of Hire: 11/17/17
No real need, as stated before this is really only used for us to organize data.

2021-04-05 21:07 UTC, Fluffacorn commented on src/svelte-html/docs/AboutTeam.svx
> +About: Ced joined the mod team after being promoted out of Loli Patroli, a group designed to moderate the undergoing lolicon problems in the porn channels. Ced faced backlash from members of the comm
This is still a draft, but I do like your idea. We do actually plan to have a wiki page on the site at some point so we could probably hyperlink something there (for example, a hyperlink to the Loli Patroli page.)

2021-04-06 04:15 UTC, Fluffacorn commented on src/svelte-html/docs/AboutUs.svx
> +So where did the community originate from? It all started on <span style="color:#FFE500">***September 20th, 2017***</span> when mashup youtuber <span style="color:#FFE500">***I am Jemboy***</span> ha
We talked and we think it's good as is, it's a tad bit long but it's nothing egregious. If you think otherwise you can think of some text to remove. Will be removing the italics though

2021-04-06 04:26 UTC, Fluffacorn commented on src/svelte-html/docs/AboutUs.svx
> +So where did the community originate from? It all started on <span style="color:#FFE500">***September 20th, 2017***</span> when mashup youtuber <span style="color:#FFE500">***I am Jemboy***</span> ha
Removed italics in my branch

2021-04-06 05:27 UTC, ryeenii commented on src/svelte-html/docs/AboutUs.svx
> +So where did the community originate from? It all started on <span style="color:#FFE500">***September 20th, 2017***</span> when mashup youtuber <span style="color:#FFE500">***I am Jemboy***</span> ha
eh, i guess we can leave it as-is then for now.

2021-04-06 05:28 UTC, ryeenii approved these changes

2021-04-06 05:35 UTC, merged